// Code generated by SQLBoiler 4.10.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package repository

var TableNames = struct {
	LeaderSupporter string
	Player          string
	Team            string
	TeamMember      string
}{
	LeaderSupporter: "leader_supporter",
	Player:          "player",
	Team:            "team",
	TeamMember:      "team_member",
}
