// Code generated by SQLBoiler 4.10.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package repository

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// TeamMember is an object representing the database table.
type TeamMember struct {
	ID     string `boil:"id" json:"id" toml:"id" yaml:"id"`
	TeamID string `boil:"team_id" json:"team_id" toml:"team_id" yaml:"team_id"`

	R *teamMemberR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L teamMemberL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var TeamMemberColumns = struct {
	ID     string
	TeamID string
}{
	ID:     "id",
	TeamID: "team_id",
}

var TeamMemberTableColumns = struct {
	ID     string
	TeamID string
}{
	ID:     "team_member.id",
	TeamID: "team_member.team_id",
}

// Generated where

var TeamMemberWhere = struct {
	ID     whereHelperstring
	TeamID whereHelperstring
}{
	ID:     whereHelperstring{field: "\"leaderseek\".\"team_member\".\"id\""},
	TeamID: whereHelperstring{field: "\"leaderseek\".\"team_member\".\"team_id\""},
}

// TeamMemberRels is where relationship names are stored.
var TeamMemberRels = struct {
	IDPlayer                  string
	Team                      string
	CandidateLeaderSupporters string
}{
	IDPlayer:                  "IDPlayer",
	Team:                      "Team",
	CandidateLeaderSupporters: "CandidateLeaderSupporters",
}

// teamMemberR is where relationships are stored.
type teamMemberR struct {
	IDPlayer                  *Player              `boil:"IDPlayer" json:"IDPlayer" toml:"IDPlayer" yaml:"IDPlayer"`
	Team                      *Team                `boil:"Team" json:"Team" toml:"Team" yaml:"Team"`
	CandidateLeaderSupporters LeaderSupporterSlice `boil:"CandidateLeaderSupporters" json:"CandidateLeaderSupporters" toml:"CandidateLeaderSupporters" yaml:"CandidateLeaderSupporters"`
}

// NewStruct creates a new relationship struct
func (*teamMemberR) NewStruct() *teamMemberR {
	return &teamMemberR{}
}

// teamMemberL is where Load methods for each relationship are stored.
type teamMemberL struct{}

var (
	teamMemberAllColumns            = []string{"id", "team_id"}
	teamMemberColumnsWithoutDefault = []string{"id", "team_id"}
	teamMemberColumnsWithDefault    = []string{}
	teamMemberPrimaryKeyColumns     = []string{"id"}
	teamMemberGeneratedColumns      = []string{}
)

type (
	// TeamMemberSlice is an alias for a slice of pointers to TeamMember.
	// This should almost always be used instead of []TeamMember.
	TeamMemberSlice []*TeamMember
	// TeamMemberHook is the signature for custom TeamMember hook methods
	TeamMemberHook func(context.Context, boil.ContextExecutor, *TeamMember) error

	teamMemberQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	teamMemberType                 = reflect.TypeOf(&TeamMember{})
	teamMemberMapping              = queries.MakeStructMapping(teamMemberType)
	teamMemberPrimaryKeyMapping, _ = queries.BindMapping(teamMemberType, teamMemberMapping, teamMemberPrimaryKeyColumns)
	teamMemberInsertCacheMut       sync.RWMutex
	teamMemberInsertCache          = make(map[string]insertCache)
	teamMemberUpdateCacheMut       sync.RWMutex
	teamMemberUpdateCache          = make(map[string]updateCache)
	teamMemberUpsertCacheMut       sync.RWMutex
	teamMemberUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var teamMemberAfterSelectHooks []TeamMemberHook

var teamMemberBeforeInsertHooks []TeamMemberHook
var teamMemberAfterInsertHooks []TeamMemberHook

var teamMemberBeforeUpdateHooks []TeamMemberHook
var teamMemberAfterUpdateHooks []TeamMemberHook

var teamMemberBeforeDeleteHooks []TeamMemberHook
var teamMemberAfterDeleteHooks []TeamMemberHook

var teamMemberBeforeUpsertHooks []TeamMemberHook
var teamMemberAfterUpsertHooks []TeamMemberHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *TeamMember) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range teamMemberAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *TeamMember) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range teamMemberBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *TeamMember) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range teamMemberAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *TeamMember) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range teamMemberBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *TeamMember) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range teamMemberAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *TeamMember) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range teamMemberBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *TeamMember) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range teamMemberAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *TeamMember) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range teamMemberBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *TeamMember) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range teamMemberAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddTeamMemberHook registers your hook function for all future operations.
func AddTeamMemberHook(hookPoint boil.HookPoint, teamMemberHook TeamMemberHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		teamMemberAfterSelectHooks = append(teamMemberAfterSelectHooks, teamMemberHook)
	case boil.BeforeInsertHook:
		teamMemberBeforeInsertHooks = append(teamMemberBeforeInsertHooks, teamMemberHook)
	case boil.AfterInsertHook:
		teamMemberAfterInsertHooks = append(teamMemberAfterInsertHooks, teamMemberHook)
	case boil.BeforeUpdateHook:
		teamMemberBeforeUpdateHooks = append(teamMemberBeforeUpdateHooks, teamMemberHook)
	case boil.AfterUpdateHook:
		teamMemberAfterUpdateHooks = append(teamMemberAfterUpdateHooks, teamMemberHook)
	case boil.BeforeDeleteHook:
		teamMemberBeforeDeleteHooks = append(teamMemberBeforeDeleteHooks, teamMemberHook)
	case boil.AfterDeleteHook:
		teamMemberAfterDeleteHooks = append(teamMemberAfterDeleteHooks, teamMemberHook)
	case boil.BeforeUpsertHook:
		teamMemberBeforeUpsertHooks = append(teamMemberBeforeUpsertHooks, teamMemberHook)
	case boil.AfterUpsertHook:
		teamMemberAfterUpsertHooks = append(teamMemberAfterUpsertHooks, teamMemberHook)
	}
}

// One returns a single teamMember record from the query.
func (q teamMemberQuery) One(ctx context.Context, exec boil.ContextExecutor) (*TeamMember, error) {
	o := &TeamMember{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "repository: failed to execute a one query for team_member")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all TeamMember records from the query.
func (q teamMemberQuery) All(ctx context.Context, exec boil.ContextExecutor) (TeamMemberSlice, error) {
	var o []*TeamMember

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "repository: failed to assign all query results to TeamMember slice")
	}

	if len(teamMemberAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all TeamMember records in the query.
func (q teamMemberQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "repository: failed to count team_member rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q teamMemberQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "repository: failed to check if team_member exists")
	}

	return count > 0, nil
}

// IDPlayer pointed to by the foreign key.
func (o *TeamMember) IDPlayer(mods ...qm.QueryMod) playerQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.ID),
	}

	queryMods = append(queryMods, mods...)

	return Players(queryMods...)
}

// Team pointed to by the foreign key.
func (o *TeamMember) Team(mods ...qm.QueryMod) teamQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.TeamID),
	}

	queryMods = append(queryMods, mods...)

	return Teams(queryMods...)
}

// CandidateLeaderSupporters retrieves all the leader_supporter's LeaderSupporters with an executor via candidate_id column.
func (o *TeamMember) CandidateLeaderSupporters(mods ...qm.QueryMod) leaderSupporterQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"leaderseek\".\"leader_supporter\".\"candidate_id\"=?", o.ID),
	)

	return LeaderSupporters(queryMods...)
}

// LoadIDPlayer allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (teamMemberL) LoadIDPlayer(ctx context.Context, e boil.ContextExecutor, singular bool, maybeTeamMember interface{}, mods queries.Applicator) error {
	var slice []*TeamMember
	var object *TeamMember

	if singular {
		object = maybeTeamMember.(*TeamMember)
	} else {
		slice = *maybeTeamMember.(*[]*TeamMember)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &teamMemberR{}
		}
		args = append(args, object.ID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &teamMemberR{}
			}

			for _, a := range args {
				if a == obj.ID {
					continue Outer
				}
			}

			args = append(args, obj.ID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`leaderseek.player`),
		qm.WhereIn(`leaderseek.player.id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Player")
	}

	var resultSlice []*Player
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Player")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for player")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for player")
	}

	if len(teamMemberAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.IDPlayer = foreign
		if foreign.R == nil {
			foreign.R = &playerR{}
		}
		foreign.R.IDTeamMember = object
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.ID == foreign.ID {
				local.R.IDPlayer = foreign
				if foreign.R == nil {
					foreign.R = &playerR{}
				}
				foreign.R.IDTeamMember = local
				break
			}
		}
	}

	return nil
}

// LoadTeam allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (teamMemberL) LoadTeam(ctx context.Context, e boil.ContextExecutor, singular bool, maybeTeamMember interface{}, mods queries.Applicator) error {
	var slice []*TeamMember
	var object *TeamMember

	if singular {
		object = maybeTeamMember.(*TeamMember)
	} else {
		slice = *maybeTeamMember.(*[]*TeamMember)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &teamMemberR{}
		}
		args = append(args, object.TeamID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &teamMemberR{}
			}

			for _, a := range args {
				if a == obj.TeamID {
					continue Outer
				}
			}

			args = append(args, obj.TeamID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`leaderseek.team`),
		qm.WhereIn(`leaderseek.team.id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Team")
	}

	var resultSlice []*Team
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Team")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for team")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for team")
	}

	if len(teamMemberAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Team = foreign
		if foreign.R == nil {
			foreign.R = &teamR{}
		}
		foreign.R.TeamMembers = append(foreign.R.TeamMembers, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.TeamID == foreign.ID {
				local.R.Team = foreign
				if foreign.R == nil {
					foreign.R = &teamR{}
				}
				foreign.R.TeamMembers = append(foreign.R.TeamMembers, local)
				break
			}
		}
	}

	return nil
}

// LoadCandidateLeaderSupporters allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (teamMemberL) LoadCandidateLeaderSupporters(ctx context.Context, e boil.ContextExecutor, singular bool, maybeTeamMember interface{}, mods queries.Applicator) error {
	var slice []*TeamMember
	var object *TeamMember

	if singular {
		object = maybeTeamMember.(*TeamMember)
	} else {
		slice = *maybeTeamMember.(*[]*TeamMember)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &teamMemberR{}
		}
		args = append(args, object.ID)
	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &teamMemberR{}
			}

			for _, a := range args {
				if a == obj.ID {
					continue Outer
				}
			}

			args = append(args, obj.ID)
		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`leaderseek.leader_supporter`),
		qm.WhereIn(`leaderseek.leader_supporter.candidate_id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load leader_supporter")
	}

	var resultSlice []*LeaderSupporter
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice leader_supporter")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on leader_supporter")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for leader_supporter")
	}

	if len(leaderSupporterAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.CandidateLeaderSupporters = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &leaderSupporterR{}
			}
			foreign.R.Candidate = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.CandidateID {
				local.R.CandidateLeaderSupporters = append(local.R.CandidateLeaderSupporters, foreign)
				if foreign.R == nil {
					foreign.R = &leaderSupporterR{}
				}
				foreign.R.Candidate = local
				break
			}
		}
	}

	return nil
}

// SetIDPlayer of the teamMember to the related item.
// Sets o.R.IDPlayer to related.
// Adds o to related.R.IDTeamMember.
func (o *TeamMember) SetIDPlayer(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Player) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"leaderseek\".\"team_member\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"id"}),
		strmangle.WhereClause("\"", "\"", 2, teamMemberPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.ID = related.ID
	if o.R == nil {
		o.R = &teamMemberR{
			IDPlayer: related,
		}
	} else {
		o.R.IDPlayer = related
	}

	if related.R == nil {
		related.R = &playerR{
			IDTeamMember: o,
		}
	} else {
		related.R.IDTeamMember = o
	}

	return nil
}

// SetTeam of the teamMember to the related item.
// Sets o.R.Team to related.
// Adds o to related.R.TeamMembers.
func (o *TeamMember) SetTeam(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Team) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"leaderseek\".\"team_member\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"team_id"}),
		strmangle.WhereClause("\"", "\"", 2, teamMemberPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.TeamID = related.ID
	if o.R == nil {
		o.R = &teamMemberR{
			Team: related,
		}
	} else {
		o.R.Team = related
	}

	if related.R == nil {
		related.R = &teamR{
			TeamMembers: TeamMemberSlice{o},
		}
	} else {
		related.R.TeamMembers = append(related.R.TeamMembers, o)
	}

	return nil
}

// AddCandidateLeaderSupporters adds the given related objects to the existing relationships
// of the team_member, optionally inserting them as new records.
// Appends related to o.R.CandidateLeaderSupporters.
// Sets related.R.Candidate appropriately.
func (o *TeamMember) AddCandidateLeaderSupporters(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*LeaderSupporter) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.CandidateID = o.ID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"leaderseek\".\"leader_supporter\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"candidate_id"}),
				strmangle.WhereClause("\"", "\"", 2, leaderSupporterPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.CandidateID = o.ID
		}
	}

	if o.R == nil {
		o.R = &teamMemberR{
			CandidateLeaderSupporters: related,
		}
	} else {
		o.R.CandidateLeaderSupporters = append(o.R.CandidateLeaderSupporters, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &leaderSupporterR{
				Candidate: o,
			}
		} else {
			rel.R.Candidate = o
		}
	}
	return nil
}

// TeamMembers retrieves all the records using an executor.
func TeamMembers(mods ...qm.QueryMod) teamMemberQuery {
	mods = append(mods, qm.From("\"leaderseek\".\"team_member\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"leaderseek\".\"team_member\".*"})
	}

	return teamMemberQuery{q}
}

// FindTeamMember retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindTeamMember(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*TeamMember, error) {
	teamMemberObj := &TeamMember{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"leaderseek\".\"team_member\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, teamMemberObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "repository: unable to select from team_member")
	}

	if err = teamMemberObj.doAfterSelectHooks(ctx, exec); err != nil {
		return teamMemberObj, err
	}

	return teamMemberObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *TeamMember) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("repository: no team_member provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(teamMemberColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	teamMemberInsertCacheMut.RLock()
	cache, cached := teamMemberInsertCache[key]
	teamMemberInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			teamMemberAllColumns,
			teamMemberColumnsWithDefault,
			teamMemberColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(teamMemberType, teamMemberMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(teamMemberType, teamMemberMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"leaderseek\".\"team_member\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"leaderseek\".\"team_member\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "repository: unable to insert into team_member")
	}

	if !cached {
		teamMemberInsertCacheMut.Lock()
		teamMemberInsertCache[key] = cache
		teamMemberInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the TeamMember.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *TeamMember) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	teamMemberUpdateCacheMut.RLock()
	cache, cached := teamMemberUpdateCache[key]
	teamMemberUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			teamMemberAllColumns,
			teamMemberPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("repository: unable to update team_member, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"leaderseek\".\"team_member\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, teamMemberPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(teamMemberType, teamMemberMapping, append(wl, teamMemberPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "repository: unable to update team_member row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "repository: failed to get rows affected by update for team_member")
	}

	if !cached {
		teamMemberUpdateCacheMut.Lock()
		teamMemberUpdateCache[key] = cache
		teamMemberUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q teamMemberQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "repository: unable to update all for team_member")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "repository: unable to retrieve rows affected for team_member")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o TeamMemberSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("repository: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), teamMemberPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"leaderseek\".\"team_member\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, teamMemberPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "repository: unable to update all in teamMember slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "repository: unable to retrieve rows affected all in update all teamMember")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *TeamMember) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("repository: no team_member provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(teamMemberColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	teamMemberUpsertCacheMut.RLock()
	cache, cached := teamMemberUpsertCache[key]
	teamMemberUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			teamMemberAllColumns,
			teamMemberColumnsWithDefault,
			teamMemberColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			teamMemberAllColumns,
			teamMemberPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("repository: unable to upsert team_member, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(teamMemberPrimaryKeyColumns))
			copy(conflict, teamMemberPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"leaderseek\".\"team_member\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(teamMemberType, teamMemberMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(teamMemberType, teamMemberMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "repository: unable to upsert team_member")
	}

	if !cached {
		teamMemberUpsertCacheMut.Lock()
		teamMemberUpsertCache[key] = cache
		teamMemberUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single TeamMember record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *TeamMember) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("repository: no TeamMember provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), teamMemberPrimaryKeyMapping)
	sql := "DELETE FROM \"leaderseek\".\"team_member\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "repository: unable to delete from team_member")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "repository: failed to get rows affected by delete for team_member")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q teamMemberQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("repository: no teamMemberQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "repository: unable to delete all from team_member")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "repository: failed to get rows affected by deleteall for team_member")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o TeamMemberSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(teamMemberBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), teamMemberPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"leaderseek\".\"team_member\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, teamMemberPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "repository: unable to delete all from teamMember slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "repository: failed to get rows affected by deleteall for team_member")
	}

	if len(teamMemberAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *TeamMember) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindTeamMember(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *TeamMemberSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := TeamMemberSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), teamMemberPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"leaderseek\".\"team_member\".* FROM \"leaderseek\".\"team_member\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, teamMemberPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "repository: unable to reload all in TeamMemberSlice")
	}

	*o = slice

	return nil
}

// TeamMemberExists checks if the TeamMember row exists.
func TeamMemberExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"leaderseek\".\"team_member\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "repository: unable to check if team_member exists")
	}

	return exists, nil
}
